export const $InputWillReceive = Symbol('input-will-receive')
export const $InputDidReceive = Symbol('input-did-receive')
export const $InputWillClear = Symbol('input-will-clear')
export const $InputDidClear = Symbol('input-did-clear')
export const $ArticleWillImport = Symbol('article-will-import')
export const $ArticleDidImport = Symbol('article-did-import')
